### ISSUE TITLE
"No value for status" error when trying to use live preview with HERO11

### ISSUE THREAD

**Issue by KonradIT** [sepp89117/GoEasyPro_Android#2]
Nice app!!

Tested it on a Pixel 6 running Android 13.

HERO11 Black running Labs FW v01.02.70

It starts the AP well (0x17), connects to wifi well, can browse media, but when trying to view livestream there's a toast saying "No value for status".

**Comment by sepp89117** [comment]
Hi Konrad,
can you tell me what the Hero11 replies to GET "http://10.5.5.9/gopro/camera/stream/start"?

For Hero5 and Hero8 the response is JSON  {"status":"0"}. In [MainActivity](https://github.com/sepp89117/GoEasyPro_Android/blob/master/app/src/main/java/com/sepp89117/goeasypro_android/MainActivity.java#L266)  i test the response for this.
There has to be a model-dependent check again

**Comment by sepp89117** [comment]
I found the following at OpenGoPro HTTP specs:
"typical use case is that the camera accepts a valid command, returns HTTP/200 (OK) and empty JSON (i.e. { }) and begins asynchronously working on the command. If an error occurs, the camera will return a standard HTTP error code and JSON with helpful error/debug information."

That is, if I check that the http response is 'OK', that should suffice. I will still test whether this also applies to Hero5 and 8.

Does everything work with your MAX?

**Comment by sepp89117** [comment]
Hello @KonradIT,

the problem should now be fixed with version 1.4.

Can you confirm it?

**Comment by KonradIT** [comment]
Ok, tested with: HERO9,HERO10,HERO11,MAX. App version 1.4

When the camera has a preset not known to the app, the text is too large and messes up the layout: https://i.imgur.com/detOTmT.png

(Water = 6 Indoor = 7)

Controls work on all cams

Media browsing: when trying to scroll down the list on H10,H11,MAX it stops, doesn't allow me to scroll down. No problem in MAX.

Live preview exits on H10,H11,MAX, it first tries to connect to AP, Android popup appears, I connect to the wifi AP, a new screen appears but it exits immediately.  

This does not happen in H9, the app correctly shows the live preview. And with little delay.

**Comment by sepp89117** [comment]
Thank you for this great report! I'll see what I can do in the days to come. Thanks again!

**Comment by KonradIT** [comment]
Trying to use it with H11 Mini, the text goes orange for some seconds then red - this is while the camera wakes up but it goes to sleep again shortly after. 

I previously paired this cam to my phone using the GoPro app to test, so the Bluetooth connection is saved in Android system. 

I tried to put it in pairing mode and select add new cam, but no dice.

Weirdly, my [gopro-ble-py](https://github.com/KonradIT/gopro-ble-py) works perfectly, connects at the first time.

I'm using the latest FW v2.00 on Mini.

**Comment by sepp89117** [comment]
Hello @KonradIT,

Thank you for your report!
I bought a Hero10 Black and have been able to improve a few things with it. See version 1.5

Unfortunately, your Hero11 is a mystery to me. Please test again with version 1.5 and if possible, please see if there are any error messages in the log, or if you see a toast.

Many thanks!

**Comment by sepp89117** [comment]
Hello @KonradIT, is there any news? I've changed a few things in the meantime. Does it work for you and do you like it?
