### ISSUE TITLE
Browse storage and live preview not working

### ISSUE THREAD

**Issue by amigax** [sepp89117/GoEasyPro_Android#3]
gopro hero 13, s22, live preview or storage browser dont seem to do anything.

**Comment by amigax** [comment]
looks like onFailure happens in browseStorage()

**Comment by amigax** [comment]
I was missing android:usesCleartextTraffic="true" in my mainfest (becausei merged this with some of my own code). works!!

**Comment by sepp89117** [comment]
Hi, I'm glad that your issue was resolved. Since this is a non-profit project, I unfortunately don't have a Hero 13 to test. You are still welcome to report further problems!

**Comment by amigax** [comment]
very cool app, seems fine on hero 13.
